### ISSUE TITLE
Error over writing Feature Survice

### ISSUE THREAD

**Issue by garrettmapp** [khibma/update-hosted-feature-service#17]
The code seems to work up until the feature service is to be updated. I am getting this error:

Starting Feature Service publish process
found Service Definition : 8f7e4c23ec2a4a4692d11355a46529b4
Created D:\update-hosted-feature-service-master\tempDir\Address_Live.sd
updated SD:   8f7e4c23ec2a4a4692d11355a46529b4
Traceback (most recent call last):
  File "D:\update-hosted-feature-service-master\update.py", line 508, in <module>
    fsID = agol.publish()
  File "D:\update-hosted-feature-service-master\update.py", line 218, in publish
    if not jsonResponse['services'][0]['success']:
KeyError: 'services'

Do you have any suggestions as to what may be causing this error?

**Comment by khibma** [comment]
Well there is an issue in the code, you shouldnt get a keyerror.  But for your problem: it failed to publish. Because the key 'services' doesnt exist, the response is most likely an error. Theres no way for me to know what this is. You'd have to print the output of **jsonResponse** itself and see what the error is.
